import type { Metadata } from "next";
import { Geist, Geist_Mono, Jersey_25, K2D } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jersey = Jersey_25({
  subsets: ['latin'],
  weight: '400',
});

const k2d = K2D({
  subsets: ['latin'],
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jersey.className} bg-black antialiased px-16 py-2`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
